### ISSUE TITLE
Unit error in flint dataset documentation

### ISSUE THREAD

**Issue by nalloway-slu** [speegled/fosdata#1]
The documentation for the `Pb` variables of the `flint` dataset are listed as being in parts per million. However, the original dataset's documentation (https://flintwaterstudy.org/2015/12/complete-dataset-lead-results-in-tap-water-for-271-flint-samples/) list these values as parts per *billion*. Checking both the original data and imported data for `fosdata` shows that the numeric values for the `Pb` variables are identical between the two datasets, so either the documentation for `flint` in `fosdata` lists the wrong unit, or the original dataset lists the wrong unit. Regardless, there is a discrepancy.

**Comment by speegled** [comment]
Fixed by commit #[b8bf5c2](https://github.com/speegled/fosdata/commit/b8bf5c2298b242b3d126f4f1b189a57486b3a50d). Thanks for bringing this to our attention!
